### ISSUE TITLE
Could you release the checkpoints for the trained network

### ISSUE THREAD

**Issue by boomboomluo** [ispc-lab/TMA#1]
Thank you very much for the excellent work you have done. But I can't get the reported results for training, can you please release the checkpoints for the trained network?

**Comment by HTLeoo** [comment]
@boomboomluo 
Sorry for my late reply. If possible, you can leave me an e-mail address. I will send both the full checkpoint and the own_split checkpoint on DSEC to you.
Or you can send an e-mail to me to make sure that I will not send the attachments to someone else.

**Comment by boomboomluo** [comment]
Thanks for your reply. My email address is luoboom@foxmail.com. I will send an e-mail to you for request. Best wishes!

**Comment by puyiwen** [comment]
@HTLeoo Hi, can you send the checkpoints to me? My email address is 291931809@qq.com，thank you very much!!

**Comment by ShangweiGuo** [comment]
@HTLeoo Hello, can you send the checkpoints to me? My email address is [2286973287@qq.com]，thank you very much : )

**Comment by Xusssssss** [comment]
@HTLeoo Hi, can you send the checkpoints to me? My email address is xsp7936@163.com，thank you very much!!

**Comment by Candy-Crusher** [comment]
@HTLeoo Hi Haotian, I've sent you an email, could you please also send me a copy of the ckpt? Many thanks!

**Comment by gurbee** [comment]
@HTLeoo Amazing work! I would like to try out the checkpoints too, it would be really helpful for my research, my email is n28111063@gs.ncku.edu.tw, appreciated!

**Comment by mptmaple** [comment]
Hi, can you send the checkpoints to me? My email address is maple_135@163.com，thank you very much!!  @HTLeoo

**Comment by wzz-z** [comment]
你好，你能把检查点发给我吗？我的邮箱地址是 1571260684@qq.com，非常感谢！！
