### ISSUE TITLE
about the crop_size in training

### ISSUE THREAD

**Issue by ZhouQianang** [ispc-lab/TMA#2]
Hello, thank you for releasing such great work! I noticed that you set the `crop_size` to `[288,384]` in `DSECdataloader` and `DSEC_split_loader`. I'm curious if this has any impact on the evaluation since the original image size is `[480,640]`. I have two questions here: 
1. Will the images be cropped during testing, for example, using CenterCrop? 
2. Should the final submission results include the ground truth of the global image ([480,640]) or just the center part? 
Thank you!

**Comment by HTLeoo** [comment]
Hi, thanks for your interest first.
1. No cropping is applied to test images, just with 480x640 resolution.
2. The final submission should conclude the full image, not a cropped one.
